# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27b8272f67bd4103175288ec10d7cfdf55b90515c5aac1a04cb795cc4e5626df84990e2152b007ce004fa1e1e5f958abe3f8296dc11693414e5ee13c8f7f003

test:
  secret_key_base: 58ccb7bcc5a80998bb86c04917c0a1d9c9fa2ba74f6c378c83a194365769ce72ddc4f6cd4f0132aaaf7adcc2729adf595877a43c1e075e8949e38c2bbf642270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
